apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  MYSQL_HOST: "cloud-sql-proxy"
  MYSQL_DB: "taskdb"
  MYSQL_PORT: "3306"
  REDIS_HOST: "10.84.243.51"
  REDIS_PORT: "6379"
  GOOGLE_REDIS_URL: "10.84.243.51"
  INITIATE_MIGRATION: "false"
  REDIS_USERNAME: "redis"
  CLOUD_SQL_CONNECTION_NAME: "task-project-daniel:europe-west3:task-api-mysql"
  DOMAIN_URL: "http://35.198.161.28"
  MONGODB_URI: "mongodb+srv://todak2000:LdmD5s93m6dJl6mY@task-management-db.31ots.mongodb.net/?retryWrites=true&w=majority&appName=task-management-db"
