apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: BASE64_ENCODED_PASSWORD
  MYSQL_USER: BASE64_ENCODED_USER
  MYSQL_PASSWORD: BASE64_ENCODED_PASSWORD
