apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-api
      env: development
  template:
    metadata:
      labels:
        app: task-api
        env: development
    spec:
      serviceAccountName: cloud-sql-service-account
      containers:
        - name: task-api
          image: gcr.io/task-project-daniel/task-api:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DOMAIN_URL
              value: "localhost-dev"
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGODB_URI
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: GOOGLE_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GOOGLE_REDIS_URL
            - name: REDIS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_USERNAME
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_REFRESH_SECRET
            - name: INITIATE_MIGRATION
              value: "true"
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          args:
            - "--structured-logs"
            - "--address=0.0.0.0"
            - "--port=3306"
            - "task-project-daniel:europe-west3:task-api-mysql"
            - "--credentials-file=/secrets/credentials.json"
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: cloud-sql-key
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: cloud-sql-key
          secret:
            secretName: cloud-sql-key
